name: 'WPS daily check in'

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:
  daily_check_in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working-invite'
        run: python WPS_accept_invitation.py
      - name: 'Working-signin'
        env: 
          WPS_SID: ${{secrets.WPS_SID}}
          run: python WPS_sign_in.py
      
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          #subject: Shanghai Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: freezuike@qq.com
          from: GitHub Actions
          content_type: text/html
